/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    VBaseDialog: typeof import('./src/components/Dialogs/VBaseDialog.vue')['default']
    VDeleteDialog: typeof import('./src/components/Dialogs/VDeleteDialog.vue')['default']
  }
}
